# Generated by Django 5.0.2 on 2024-04-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchgrass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.CharField(default='', max_length=500),
        ),
    ]
